# syntax=docker/dockerfile:1
FROM python:3.9
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
WORKDIR /code
COPY ./backend /code
COPY ../core /code/core
RUN pip install -r requirements.txt
EXPOSE 5000

CMD python3 src/manage.py runserver 0.0.0.0:5000 --noreload