version: "3.9"
services:
    redis:
        image: redis/redis-stack:latest
        container_name: redis
        # ports:
        #     - "6379:6379"
        restart: always
        network_mode: "service:nginx"
        volumes:
            - /home/ubuntu/redis:/home/redis
    checklet:
        image: splacorn/checklet:latest
        container_name: checklet
        # ports:
        #     - "3000:3000"
        restart: always
        environment:
            - OPENAI_API_KEY=${OPENAI_API_KEY}
        network_mode: "service:nginx"
    nginx:
        image: splacorn/checklet-nginx:latest
        container_name: nginx
        volumes:
            - /etc/letsencrypt:/etc/letsencrypt:ro
        restart: always
        ports:
            - "80:80"
            - "443:443"
            - "6379:6379"
            - "8001:8001"
