import { mackinac } from "@/app/fonts";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

// TODO: consider migrating to nextjs 13 and move all the pages from pages/ to app/ directory (so we can have server-side rendering)
//for now, I'll stick with _app.tsx
// use this migration guide: https://nextjs.org/docs/app/building-your-application/upgrading/app-router-migration
// Step 4: Migrating Pages shows how much it's changed
export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body className={`${mackinac.variable} ${inter.className}`}>
                {children}
            </body>
        </html>
    );
}
