import { lora, mackinac } from "@/app/fonts";
import { mixpanelTrack } from "@/utils";
import mixpanel from "mixpanel-browser";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { useEffect } from "react";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import "tailwindcss/tailwind.css";
import "./globals.css";

const mixPanelDevToken = "94ac9cfab8d2280edba19b31b2937926";
const mixPanelProdToken = "dc8c89187149505f2392759f15e0fd4d";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

// https://nextjs.org/docs/app/building-your-application/upgrading/app-router-migration
//Pages in the app directory are Server Components by default. This is different from the pages directory where pages are Client Components.
// basically, anything in the pages directory does NOT use the RootLayout automatically.
// see hte Step 4: Migrating Pages section

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    useEffect(() => {
        if (window.location.hostname === "localhost") {
            mixpanel.init(mixPanelDevToken);
        } else {
            mixpanel.init(mixPanelProdToken);
        }
        mixpanelTrack("Opened app");
    }, []);
    debugger;
    return (
        <html lang="en">
            <body
                className={`${lora.variable} ${mackinac.variable} ${inter.className}`}
            >
                {/* <ClientContextProvider>{children}</ClientContextProvider> */}
                <ToastContainer />
            </body>
        </html>
    );
}

// function MyApp({ Component, pageProps }: AppProps): JSX.Element {
//     if (typeof window !== "undefined" && Component) {
//         return (
//             <>
//                 <div className={`${lora.variable} ${mackinac.variable}`}>
//                     <Component {...pageProps} />
//                 </div>
//             </>
//         );
//     }
//     return <></>;
// }

// export default MyApp;
