export const MAX_CHECKER_DESC_LEN = 700;
export const MAX_CHECKER_NAME_LEN = 150;

export const MAX_CHECK_NAME_LEN = 100;
export const MAX_CHECK_DESC_LEN = 700;
export const MAX_CHECK_INSTR_LEN = 1500;
export const MAX_CHECK_CATEGORY_LEN = 100;
export const MAX_POSITIVE_EX_ORIGINAL_TEXT_LEN = 500;
export const MAX_POSITIVE_EX_EDITED_TEXT_LEN = 500;
