name: Deploy backend

defaults:
  run:
    working-directory: backend

on:
  push:
    branches:
      - main
      - master

jobs:
  deploy-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Deploy Backend
         run: ./deploy.sh ${{ GITHUB_SHA }}
